name: Build & Release

on:
  push:
    branches:
      - master

jobs:
  MACOSX:
    name: Mac OS X
    runs-on: [ macos-15 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          ./install_dependencies_macosx.sh
      - name: Configure
        run: |
          cd "${{ github.workspace }}"
          mkdir build
          cd build
          cmake ..
      - name: Build
        run: |
          cd "${{ github.workspace }}/build"
          make -j4
      - name: Produce binary
        run: |
          cd "${{ github.workspace }}"
          ./create_release.sh
      - name: Zip binary
        run: |
          cd "${{ github.workspace }}/bin"
          zip -vr d2tm.zip . -x "*.DS_Store"
      - name: Produce release name
        run: |
          cd "${{ github.workspace }}"
          mkdir -p out/nightly
          FILE_NAME=D2TM-$(date +'%Y%m%d').$(git rev-parse --short HEAD).zip
          cp bin/d2tm.zip "out/nightly/$FILE_NAME"
          echo "RELEASE_NAME=$FILE_NAME" >> $GITHUB_ENV
      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RELEASE_NAME }}
          path: build/d2tm.zip
      - name: Generate index.html
        run: |
          echo '<!DOCTYPE html>' > out/index.html
          echo '<html><head><meta charset="UTF-8"><title>D2TM Nightly Builds</title></head><body>' >> out/index.html
          echo '<h1>Dune 2 - The Maker: Nightly Builds</h1><ul>' >> out/index.html
          
          for zip in $(ls out/nightly/*.zip | sort -r); do
            file=$(basename "$zip")
            echo "<li><a href=\"nightly/$file\">$file</a></li>" >> out/index.html
          done
          
          echo '</ul></body></html>' >> out/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          keep_files: true